### PR TITLE
about_in_settings addressing issue #3

### PR DESCRIPTION
**Pull request by AdiAr11**
I've added About us button in settings page which addresses issue #3 and displays information when clicked

### CODE REVIEW

**Comment by justdvnsh** [comment]
Hi @AdiAr11 . can you provide a screenshot of the same.

**Review by justdvnsh — CHANGES_REQUESTED** [review]
I have reviewed the files. the code looks good to me. Just make sure to include screenshots in the case of a ui change

**Comment by AdiAr11** [comment]
> I have reviewed the files. the code looks good to me. Just make sure to include screenshots in the case of a ui change

very sorry, i'll add the screenshots and take care of it next time.

**Comment by AdiAr11** [comment]
settings_about1
settings_about2
settings_about3

**Review by justdvnsh — APPROVED** [review]
@AdiAr11 Looks good to me. Thank you for your contributions. Happy coding.

**Comment by AdiAr11** [comment]
> @AdiAr11 Looks good to me. Thank you for your contributions. Happy coding.

thank you so much !!

**Pull request merged**
