### PR TITLE
Implementation of the function parseAnimeDetails in class Parser.

### PR DESCRIPTION
**Pull request by Bhyan**
Hi @justdvnsh, I've finished issue #32. I used the structure Java that I know best and any articles of test  on Kotlin, if you think another structure better, let me know and I'll update. i don't know how to assess the coverage of tests in Kotlin, but i think i covered all possibles test from parseAnimeDetails function.

### CODE REVIEW

**Review by justdvnsh — CHANGES_REQUESTED** [review]
Hi @Bhyan You did great. Thank you so much for your contributions. Can you just attach the screenshot of the passed tests. The code looks good to me.

**Comment by Bhyan** [comment]
Hi @justdvnsh this screenshot is satisfy ?

Captura de tela de 2021-10-15 14-28-31

**Review by justdvnsh — APPROVED** [review]
@Bhyan The code looks good to me. Thank you for your contributions.

**Comment by Bhyan** [comment]
Can i get another issues of tests ? If nobody get of course.

**Comment by justdvnsh** [comment]
@Bhyan Sure. Just comment on any issue you like and tag me. I'll assign it to you. You can comment on multiple issues if you like. Thanks

**Pull request merged**
