### PR TITLE
added fragment transition animations

### PR DESCRIPTION
**Pull request by shubham423**
## This pr adresses issue #37 

# Proof of work

https://user-images.githubusercontent.com/57858666/136084705-86c970fd-b274-4354-ba90-00a4a2ba3f4c.mp4

### CODE REVIEW

**Comment by justdvnsh** [comment]
Hi @shubham423 . Thanks for your contribution.

**Comment by shubham423** [comment]
thanks @justdvnsh your project was quite helpfull for many first time contributors like me

**Comment by justdvnsh** [comment]
@shubham423 . I am glad it could help. Thanks for your contribution and I hope you would keep contributing to the project. I am soon going to add some bigger and difficult tasks as well. Moreover, I am also going to launch my second project quite soon. Please contribute in that repo too, if you'd like

**Comment by shubham423** [comment]
sure @justdvnsh i would love to contribute in this or your future projects

**Pull request merged**
