### PR TITLE
talk_to_us button added 

### PR DESCRIPTION
**Pull request by AdiAr11**
I've added Talk To Us button addressing issue #76

### CODE REVIEW

**Comment by AdiAr11** [comment]
video demo showing functionality of talk to us button

https://user-images.githubusercontent.com/54585121/137514212-05b50891-2889-4960-94ac-a7f9a4ca0be2.mp4

**Review by justdvnsh — CHANGES_REQUESTED** [review]
The code looks good to me @AdiAr11 . Please resolve the merge conflicts too. Thank you for your contributions.

**Comment by AdiAr11** [comment]
Resolved the conflicts. Hope its fine now. Thank you

**Review by justdvnsh — APPROVED** [review]
@AdiAr11 LGTM. Thank you for your contributions. Thanks

**Comment by AdiAr11** [comment]
> @AdiAr11 LGTM. Thank you for your contributions. Thanks

Thank you so much !

**Pull request merged**
