### PR TITLE
General error layout

### PR DESCRIPTION
**Pull request by shivamparihar12**
So here is the another pr. since there are no conflicts and .idea files are also deleted then i guess this one must be fine. if not so then please tell what should i do now.

### CODE REVIEW

**Comment by justdvnsh** [comment]
@shivamparihar12 . I am accepting this PR, and i will delete the .idea files myself. But for further Pr's please make sure to update your repo with develop branch. It has the .gitignore file which will automatically ignore the .git files from the commit.

**Comment by justdvnsh** [comment]
Also, before i merge the pr, can you share a screenshot of the layout ?

**Comment by shivamparihar12** [comment]
Thanks and sorry for the trouble.
here is the screenshot of the layout.
Screenshot (697)

**Comment by justdvnsh** [comment]
@shivamparihar12 No worries. I can handle that. Also, please star the repo, and thanks for your contribution

**Pull request merged**
